export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const SAVE_WORKOUT_START = 'SAVE_WORKOUT_START';
export const SAVE_WORKOUT_SUCCESS = 'SAVE_WORKOUT_SUCCESS';
export const SAVE_WORKOUT_FAIL = 'SAVE_WORKOUT_FAIL';

export const FETCH_WORKOUTS_START = 'FETCH_WORKOUTS_START';
export const FETCH_WORKOUTS_SUCCESS = 'FETCH_WORKOUTS_SUCCESS';
export const FETHC_WORKOUTS_FAIL = 'FETCH_WORKOUTS_FAIL';

export const LOGOUT = 'LOGOUT';